Repository claytonmsafranek/UNO-CSLC-Ticket-Portal, pull requests merged in 2023-05, with the labels that each got.

#92 Add Tutor Admin
  portal/.flake8
  portal/app/__init__.py
  portal/app/blueprints/__init__.py
  portal/app/blueprints/admin.py
  portal/app/blueprints/auth.py
  portal/app/blueprints/views.py
  portal/app/model.py
  portal/app/templates/admin-console.html
  portal/app/templates/admin-course.html
  portal/app/templates/admin-tutors.html
  portal/app/templates/base.html
  portal/app/templates/view_tickets.html
  portal/app/util.py
  portal/tests/__init__.py
  portal/tests/conftest.py
  portal/tests/test_admin.py
  portal/tests/test_create_ticket.py
  portal/tests/test_edit_ticket.py
  portal/tests/test_portal_landing.py
  portal/tests/test_update_ticket.py
Labels: enhancement

#110 Effective permission of inactive tutors is now Student
  portal/app/blueprints/views.py
  portal/app/util.py
Labels: bug

#96 Add Course, Semester, Professor, & Section
  portal/app/blueprints/admin.py
  portal/app/model.py
  portal/app/templates/admin-console.html
  portal/app/templates/admin-course.html
  portal/app/templates/admin-professor.html
  portal/app/templates/admin-sections.html
  portal/app/templates/admin-semester.html
  portal/app/templates/base.html
  portal/app/util.py
  portal/tests/conftest.py
  portal/tests/test_admin.py
  portal/tests/test_admin_add_tutors.py
  portal/tests/test_admin_crs_sec_sem_prof.py
  portal/tests/test_admin_edit_courses.py
  portal/tests/test_admin_edit_tutors.py
  portal/tests/test_admin_remove_tutors.py
Labels: enhancement

#126 Integrate courses with frontend
  portal/.flake8
  portal/app/__init__.py
  portal/app/blueprints/admin.py
  portal/app/blueprints/views.py
  portal/app/model.py
  portal/app/static/js/course_selector.js
  portal/app/templates/admin-professor.html
  portal/app/templates/admin-sections.html
  portal/app/templates/admin-semester.html
  portal/app/templates/base.html
  portal/app/templates/create-ticket.html
  portal/app/templates/view_tickets.html
  portal/tests/conftest.py
  portal/tests/test_create_ticket.py
  portal/tests/test_create_ticket_guest.py
  portal/tests/test_edit_ticket.py
  portal/tests/test_update_ticket.py
Labels: bug, enhancement

#127 Update README.md
  README.md
Labels: bug
